[package]
name = "exa_blanc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8.6"
strum = "0.24"
strum_macros = "0.24"
card-validate = "2.1"
